# Generated by Django 3.1.5 on 2021-01-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inn', models.CharField(db_index=True, default=None, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('inn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ogrn', models.CharField(max_length=20)),
                ('kpp', models.CharField(max_length=20)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal_entity.ceo')),
            ],
        ),
    ]
