# Generated by Django 3.1.5 on 2021-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('inn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('kpp', models.CharField(max_length=20)),
                ('bik', models.CharField(db_index=True, max_length=20, unique=True)),
                ('correspondent_account', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
